"""empty message

Revision ID: 157d95225531
Revises: beffb4cf552c
Create Date: 2021-07-18 15:53:48.397631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157d95225531'
down_revision = 'beffb4cf552c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
