"""empty message

Revision ID: 1c3223757420
Revises: e696c7e67974
Create Date: 2021-07-17 09:58:20.504982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3223757420'
down_revision = 'e696c7e67974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
