"""amogus in real life

Revision ID: 59f58ec77d68
Revises: 
Create Date: 2021-07-06 16:30:24.013904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f58ec77d68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'discord_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
