"""empty message

Revision ID: 6e54ec14aeec
Revises: 5f2e3bfa372c
Create Date: 2021-07-16 15:57:54.797628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e54ec14aeec'
down_revision = '5f2e3bfa372c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
