"""empty message

Revision ID: 7b59ede1dc10
Revises: ca641829a5e0
Create Date: 2021-07-16 23:12:42.092836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b59ede1dc10'
down_revision = 'ca641829a5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('guild',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('guild',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
