"""empty message

Revision ID: beffb4cf552c
Revises: 0a7aaa81f953
Create Date: 2021-07-18 15:49:45.478182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beffb4cf552c'
down_revision = '0a7aaa81f953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
