"""why do you do this to me SQLAlchemy?

Revision ID: ca641829a5e0
Revises: 59f58ec77d68
Create Date: 2021-07-16 20:38:30.663002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca641829a5e0'
down_revision = '59f58ec77d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.add_column(sa.Column('guild', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("guild")
    # ### end Alembic commands ###
