"""empty message

Revision ID: e2e97d06666c
Revises: 6e54ec14aeec
Create Date: 2021-07-16 19:44:48.847846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e97d06666c'
down_revision = '6e54ec14aeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
