"""empty message

Revision ID: e96e6f335428
Revises: e5ec4271c947
Create Date: 2021-07-18 15:59:02.019214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96e6f335428'
down_revision = 'e5ec4271c947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
